Reprise globale du package

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -1,24 +1,54 @@
 #!/bin/bash
 
-# Récupère les infos de l'application.
-app=$YNH_APP_INSTANCE_NAME
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
 
-# Source app helpers
+# Exit on command errors and treat unset variables as an error
+set -eu
+
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+if [ ! -e .fonctions ]; then
+	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
+	sudo cp ../settings/scripts/.fonctions ./.fonctions
+	sudo chmod a+rx .fonctions
+fi
+source .fonctions
 source /usr/share/yunohost/helpers
 
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
+
 version=$(ynh_app_setting_get $app version)
-port=$(ynh_app_setting_get $app port)
 
-
-# The parameter $1 is the backup directory location
-# which will be compressed afterward
-backup_dir=$1/apps/$app
-sudo mkdir -p "$backup_dir"
+#=================================================
+# SPECIFIC BACKUP
+#=================================================
+# BACKUP OF THE APT SOURCE
+#=================================================
 
 # Copie des fichiers spécifiques à l'application
 if [ $version = "B" ]
 then
-	sudo cp -a /etc/apt/sources.list.d/minidlna.list $backup_dir/
+	ynh_backup /etc/apt/sources.list.d/minidlna.list minidlna.list
 fi
-sudo cp -a /etc/sysctl.d/90-inotify_minidlna.conf $backup_dir/
-sudo cp -a /etc/minidlna.conf $backup_dir/
+
+#=================================================
+# BACKUP OF THE INOTIFY'S CONFIG
+#=================================================
+
+ynh_backup /etc/sysctl.d/90-inotify_minidlna.conf inotify
+
+#=================================================
+# BACKUP OF THE CONFIG OF MINIDLNA
+#=================================================
+
+ynh_backup /etc/minidlna.conf minidlna.conf
diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,46 +1,67 @@
 #!/bin/bash
 
-source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-CLEAN_SETUP () {
-# Nettoyage des résidus d'installation non pris en charge par le script remove.
-# Pas de nettoyage supplémentaire nécessaire ici...
-	echo ""
-}
-TRAP_ON	# Active trap pour arrêter le script si une erreur est détectée.
-
-# Retrieve arguments
-version=$YNH_APP_ARG_VERSION
-
-app=$YNH_APP_INSTANCE_NAME
-
-# Source app helpers
+source .fonctions
 source /usr/share/yunohost/helpers
 
-# Vérifie que les variables ne sont pas vides.
-CHECK_VAR "$app" "app name not set"
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
 
+ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
 
-FIND_PORT 48200	# Cherche un port libre.
+#=================================================
+# RETRIEVE ARGUMENTS FROM THE MANIFEST
+#=================================================
+
+version=$YNH_APP_ARG_VERSION
+app=$YNH_APP_INSTANCE_NAME
+
+#=================================================
+# CHECK THE DEBIAN'S CODENAME
+#=================================================
+
+codename=$(lsb_release -a 2>/dev/null | grep Codename | cut -f 2)
+test -z "$codename" && (ynh_die "codename empty")
+
+#=================================================
+# STANDARD MODIFICATIONS
+#=================================================
+# FIND AND OPEN A PORT
+#=================================================
+
+port=$(ynh_find_port 48200)	# Cherche un port libre.
 
 # Ouvre les ports dans le firewall
-sudo yunohost firewall allow --no-upnp TCP $port > /dev/null 2>&1
-sudo yunohost firewall allow --no-upnp UDP 1900 > /dev/null 2>&1	# Découverte SSDP pour UPNP.
+ALL_QUIET sudo yunohost firewall allow --no-upnp TCP $port
+ALL_QUIET sudo yunohost firewall allow --no-upnp UDP 1900	# Découverte SSDP pour UPNP.
+ynh_app_setting_set $app port $port
 
 # Enregistre les infos dans la config YunoHost
 ynh_app_setting_set $app version ${version:0:1}
-ynh_app_setting_set $app port $port
 
-# Création du dossier yunohost.multimedia
-wget -nv https://github.com/maniackcrudelis/yunohost.multimedia/archive/master.zip
+#=================================================
+# CREATE YUNOHOST.MULTIMEDIA DIRECTORY
+#=================================================
+
+wget -nv https://github.com/YunoHost-Apps/yunohost.multimedia/archive/master.zip
 unzip master.zip
 sudo ./yunohost.multimedia-master/script/ynh_media_build.sh
+
+#=================================================
+# SPECIFIC SETUP
+#=================================================
+# INSTALL MINIDLNA
+#=================================================
 
 # Installation du paquet minidlna et ses dépendances
 if [ ${version:0:1} = "B" ]
 then	# Installation de la version minidlna disponible dans backport. (En cas de problème avec la version actuelle des dépots)
-	codename=$(lsb_release -a 2>/dev/null | grep Codename | cut -f 2)
-	test -z "$codename" && (echo "codename empty" && false)
 	sudo sed -i "s@__CODENAME__@$codename@g" ../conf/minidlna.list
 	sudo cp -a ../conf/minidlna.list /etc/apt/sources.list.d/
 	sudo apt-get update
@@ -49,14 +70,27 @@ else	# Installation de la version minidlna des dépots courants.
 	sudo apt-get update
 	sudo apt-get -y install minidlna
 fi
+ynh_app_setting_set $app version ${version:0:1}
+
+#=================================================
+# INCREASE INOTIFY'S LIMITS
+#=================================================
 
 # Augmentation du nombre maximum de fichiers surveillés par inotify.
 sudo cp -a ../conf/90-inotify_minidlna.conf /etc/sysctl.d/
 # Et rechargement de la config du noyau.
 sudo sysctl --system
 
+#=================================================
+# ENABLE SERVICE IN ADMIN PANEL
+#=================================================
+
 # Ajoute le service au monitoring de Yunohost.
 sudo yunohost service add minidlna --log "/var/log/minidlna.log"
+
+#=================================================
+# CONFIGURE MINIDLNA
+#=================================================
 
 # Modifie la configuration de minidlna
 sudo sed -i 's@^#*media_dir=.*@media_dir=/home/yunohost.multimedia/share@' /etc/minidlna.conf
@@ -65,8 +99,9 @@ sudo sed -i "s/^#*friendly_name=.*/friendly_name=Yunohost DLNA/" /etc/minidlna.c
 sudo sed -i "s/^#*root_container=.*/root_container=B/" /etc/minidlna.conf
 STORE_MD5_CONFIG "minidlna.conf" "/etc/minidlna.conf"	# Enregistre la somme de contrôle du fichier de config
 
-# Redémarre minidlna pour prendre en compte la nouvelle configuration
-sudo service minidlna restart
+#=================================================
+# RESTART MINIDLNA'S SERVICE
+#=================================================
 
-# Régénère la configuration de SSOwat
-sudo yunohost app ssowatconf
+# Redémarre minidlna pour prendre en compte la nouvelle configuration
+sudo systemctl restart minidlna
diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,31 +1,60 @@
 #!/bin/bash
 
-# Récupère les infos de l'application.
-app=$YNH_APP_INSTANCE_NAME
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
 
-# Source app helpers
+# Exit on command errors and treat unset variables as an error
+set -eu
+
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+if [ ! -e .fonctions ]; then
+	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
+	sudo cp ../settings/scripts/.fonctions ./.fonctions
+	sudo chmod a+rx .fonctions
+fi
+source .fonctions
 source /usr/share/yunohost/helpers
+
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
 
 version=$(ynh_app_setting_get $app version)
 port=$(ynh_app_setting_get $app port)
 
-# The parameter $1 is the uncompressed restore directory location
-backup_dir=$1/apps/$app
+#=================================================
+# SPECIFIC RESTORE
+#=================================================
+# OPEN PORTS
+#=================================================
 
-# Ouvre les ports dans le firewall
 sudo yunohost firewall allow --no-upnp TCP $port > /dev/null 2>&1
-sudo yunohost firewall allow --no-upnp UDP 1900 > /dev/null 2>&1	# Découverte SSDP pour UPNP.
+sudo yunohost firewall allow --no-upnp UDP 1900	 > /dev/null 2>&1 # Découverte SSDP pour UPNP.
 
-# Création du dossier yunohost.multimedia
+#=================================================
+# CREATE YUNOHOST.MULTIMEDIA DIRECTORY
+#=================================================
+
 wget -nv https://github.com/maniackcrudelis/yunohost.multimedia/archive/master.zip
 unzip master.zip
 sudo ./yunohost.multimedia-master/script/ynh_media_build.sh
 
-# Installation du paquet minidlna et ses dépendances
+#=================================================
+# INSTALL MINIDLNA
+#=================================================
+
 if [ ${version:0:1} = "B" ]
 then	# Installation de la version minidlna disponible dans backport. (En cas de problème avec la version actuelle des dépots)
 	codename=$(lsb_release -a 2>/dev/null | grep Codename | cut -f 2)
-	sudo cp -a $backup_dir/minidlna.list /etc/apt/sources.list.d/
+	sudo cp -a ./minidlna.list /etc/apt/sources.list.d/
 	sudo sed -i "s@ [a-z]*-backports@ $codename-backports@g" /etc/apt/sources.list.d/minidlna.list
 	sudo apt-get update
 	sudo apt-get -t $codename-backports -y install minidlna
@@ -34,14 +63,19 @@ else	# Installation de la version minidlna des dépots courants.
 	sudo apt-get -y install minidlna
 fi
 
-# Copie des fichiers spécifiques à l'application
-sudo cp -a $backup_dir/90-inotify_minidlna.conf /etc/sysctl.d/
+#=================================================
+# RESTORE INOTIFY'S CONFIG
+#=================================================
+
+sudo cp -a ./inotify /etc/sysctl.d/90-inotify_minidlna.conf
 sudo sysctl --system
 
-sudo cp -a $backup_dir/minidlna.conf /etc/
-sudo service minidlna restart
+sudo cp -a ./minidlna.conf /etc/
+sudo systemctl restart minidlna
+
+#=================================================
+# ENABLE SERVICE IN ADMIN PANEL
+#=================================================
 
 # Ajoute le service au monitoring de Yunohost.
 sudo yunohost service add minidlna --log "/var/log/minidlna.log"
-
-sudo yunohost app ssowatconf
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,22 +1,45 @@
 #!/bin/bash
 
-source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-# Récupère les infos de l'application.
-app=$YNH_APP_INSTANCE_NAME
-
-# Source app helpers
+source .fonctions
 source /usr/share/yunohost/helpers
+
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
 
 version=$(ynh_app_setting_get $app version)
 port=$(ynh_app_setting_get $app port)
 
-# Mise à jour du dossier yunohost.multimedia
+#=================================================
+# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
+#=================================================
+
+BACKUP_BEFORE_UPGRADE	# Backup the current version of the app
+ynh_clean_setup () {
+	BACKUP_FAIL_UPGRADE	# restore it if the upgrade fails
+}
+ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
+
+#=================================================
+# UPGRADE THE YUNOHOST.MULTIMEDIA DIRECTORY
+#=================================================
+
 wget -nv https://github.com/maniackcrudelis/yunohost.multimedia/archive/master.zip
 unzip master.zip
 sudo ./yunohost.multimedia-master/script/ynh_media_build.sh
 
-# Mise à jour éventuelle du paquet minidlna
+#=================================================
+# UPGRADE MINIDLNA
+#=================================================
+
 if [ $version = "B" ]
 then	# Installation de la version minidlna disponible dans backport. (En cas de problème avec la version actuelle des dépots)
 	codename=$(lsb_release -a 2>/dev/null | grep Codename | cut -f 2)
@@ -29,13 +52,25 @@ else	# Installation de la version minidlna des dépots courants.
 	sudo apt-get -y install minidlna
 fi
 
+#=================================================
+# INCREASE INOTIFY'S LIMITS
+#=================================================
+
 # Augmentation du nombre maximum de fichiers surveillés par inotify.
 sudo cp -a ../conf/90-inotify_minidlna.conf /etc/sysctl.d/
 # Et rechargement de la config du noyau.
 sudo sysctl --system
 
+#=================================================
+# ENABLE SERVICE IN ADMIN PANEL
+#=================================================
+
 # Ajoute le service au monitoring de Yunohost.
 sudo yunohost service add minidlna --log "/var/log/minidlna.log"
+
+#=================================================
+# CONFIGURE MINIDLNA
+#=================================================
 
 # Modifie la configuration de minidlna
 CHECK_MD5_CONFIG "minidlna.conf" "/etc/minidlna.conf"	# Créé un backup du fichier de config si il a été modifié.
@@ -44,8 +79,9 @@ sudo sed -i "s/^#*port=.*/port=$port/" /etc/minidlna.conf
 sudo sed -i "s/^#*friendly_name=.*/friendly_name=Yunohost DLNA/" /etc/minidlna.conf
 sudo sed -i "s/^#*root_container=.*/root_container=B/" /etc/minidlna.conf
 
-# Redémarre minidlna pour prendre en compte la nouvelle configuration
-sudo service minidlna restart
+#=================================================
+# RESTART MINIDLNA'S SERVICE
+#=================================================
 
-# Régénère la configuration de SSOwat
-sudo yunohost app ssowatconf
+# Redémarre minidlna pour prendre en compte la nouvelle configuration
+sudo systemctl restart minidlna
